# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [7]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.random.randint(10, size=(10))

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.random.randint(10, size=(10,3))

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.random.randint(10, size=(10,3,3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((10,), 1, dtype('int64'), 10, numpy.ndarray)

In [9]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((10, 3), 2, dtype('int64'), 30, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr3.size, type(arr3)

((10, 3, 3), 3, dtype('int64'), 90, numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(arr2)
df

0  1  2
0  0  6  8
1  1  9  4
2  7  5  7
3  7  7  7
4  8  9  9
5  9  4  8
6  4  4  3
7  8  5  4
8  5  7  0
9  8  1  7

In [18]:
# Create an array of shape (10, 2) with only ones
arr4 = np.ones(shape=(10,2))
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# Create an array of shape (7, 2, 3) of only zeros
arr5 = np.zeros(shape=(7, 2, 3))
arr5

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
# Create an array within a range of 0 and 100 with step 3
arr6= np.arange(0,100,3)
arr6

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr7 = np.random.randint(10, size=(7,2))
arr7

array([[3, 4],
       [2, 4],
       [9, 0],
       [7, 2],
       [1, 4],
       [4, 0],
       [9, 2]])

In [23]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr8 = np.random.random(size=(3,5))
arr8

array([[0.86636075, 0.69167042, 0.23746347, 0.63245669, 0.93617903],
       [0.47761972, 0.06854818, 0.99011322, 0.15536164, 0.26290491],
       [0.27243638, 0.96392054, 0.49144654, 0.8627499 , 0.06984539]])

In [25]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr9= np.random.randint(10, size=(4,6))
arr9

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [30]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(40)
arr10 = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(arr10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Find the 0'th index of the latest array you created
arr10[0]

array([7, 8, 6, 9, 9, 3, 2])

In [34]:
# Get the first 2 rows of latest array you created
arr10[:2]

array([[7, 8, 6, 9, 9, 3, 2],
       [8, 3, 4, 8, 4, 1, 2]])

In [35]:
# Get the first 2 values of the first 2 rows of the latest array
arr10[:2,0]

array([7, 8])

In [37]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr11 = np.ones(shape=(3,5))
arr12 = np.random.randint(10, size=(3,5))

In [38]:
# Add the two arrays together
arr11 + arr12

array([[ 4.,  8.,  8.,  2.,  4.],
       [ 6.,  3.,  3.,  4.,  8.],
       [10.,  4.,  3.,  3.,  6.]])

In [40]:
# Create another array of ones of shape (5, 3)
arr13 = np.ones(shape=(5,3))

In [41]:
# Try add the array of ones and the other most recent array together
arr12+arr13

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [48]:
# Create another array of ones of shape (3, 5)
arr14 = np.ones(shape=(3,5))

In [49]:
# Subtract the new array of ones from the other most recent array
arr15 = arr12-arr14

In [54]:
# Multiply the ones array with the latest array
arr16 = arr15*arr14
arr16

array([[2., 6., 6., 0., 2.],
       [4., 1., 1., 2., 6.],
       [8., 2., 1., 1., 4.]])

In [56]:
# Take the latest array to the power of 2 using '**'
arr17 = arr16**2
arr17

array([[ 4., 36., 36.,  0.,  4.],
       [16.,  1.,  1.,  4., 36.],
       [64.,  4.,  1.,  1., 16.]])

In [58]:
# Do the same thing with np.square()
np.square(arr16)

array([[ 4., 36., 36.,  0.,  4.],
       [16.,  1.,  1.,  4., 36.],
       [64.,  4.,  1.,  1., 16.]])

In [59]:
# Find the mean of the latest array using np.mean()
np.mean(arr16)

3.066666666666667

In [61]:
# Find the maximum of the latest array using np.max()
np.max(arr16)

8.0

In [62]:
# Find the minimum of the latest array using np.min()
np.min(arr16)

0.0

In [63]:
# Find the standard deviation of the latest array
np.std(arr16)

2.3513589451397863

In [64]:
# Find the variance of the latest array
np.var(arr16)

5.528888888888889

In [65]:
# Reshape the latest array to (3, 5, 1)
arr16.reshape(3,5,1)

array([[[2.],
        [6.],
        [6.],
        [0.],
        [2.]],

       [[4.],
        [1.],
        [1.],
        [2.],
        [6.]],

       [[8.],
        [2.],
        [1.],
        [1.],
        [4.]]])

In [66]:
# Transpose the latest array
arr16.T

array([[2., 4., 8.],
       [6., 1., 2.],
       [6., 1., 1.],
       [0., 2., 1.],
       [2., 6., 4.]])

What does the transpose do?

In [67]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ar1 = np.random.randint(10, size=(3,3))
ar2 = np.random.randint(10, size=(3,2))

In [68]:
# Perform a dot product on the two newest arrays you created
np.dot(ar1, ar2)

array([[ 30,  44],
       [ 69, 121],
       [100, 126]])

In [70]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ar3 = np.random.randint(10, size=(4,3))
ar4 = np.random.randint(10, size=(4,3))

In [71]:
# Perform a dot product on the two newest arrays you created
np.dot(ar3, ar4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [72]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(ar3, ar4.T)

array([[ 98,  71,  88,  50],
       [ 62,  41,  65,   5],
       [ 87,  84,  91,  60],
       [109,  85, 114,  35]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [73]:
# Compare the two arrays with '>'
ar3>ar4

array([[False, False, False],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

In [74]:
# Compare the two arrays with '>='
ar3>=ar4

array([[False, False, False],
       [ True, False, False],
       [False,  True, False],
       [ True, False,  True]])

In [75]:
# Find which elements of the first array are greater than 7
ar3>7

array([[False, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False]])

In [76]:
# Which parts of each array are equal? (try using '==')
ar3==ar4

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [78]:
# Sort one of the arrays you just created in ascending order
np.sort(ar3)

array([[4, 5, 5],
       [0, 1, 8],
       [1, 4, 8],
       [2, 5, 9]])

In [79]:
# Sort the indexes of one of the arrays you just created
np.argsort(ar3)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [82]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar3)

11

In [83]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar3)

3

In [84]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ar3, axis=1)

array([1, 2, 2, 2])

In [85]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ar3, axis=0)

array([1, 1, 0])

In [89]:
# Create an array of normally distributed random numbers
ar5 = np.random.randint(10, size=(10))
ar5

array([3, 2, 4, 9, 7, 6, 7, 7, 3, 4])

In [93]:
# Create an array with 10 evenly spaced numbers between 1 and 100
ar6 = np.arange(1,100,10)
ar6

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.